### ISSUE TITLE
xcube server to render RGB images

### ISSUE THREAD

**Issue by forman** [dcs4cop/xcube#101]
**Is your feature request related to a problem? Please describe.**

A number DCS4COP users need RGB images computed from some waveband combination.

**Describe the solution you'd like**

This may be initially implemented (for performance testing) as a configured "memory" dataset that computes R, G, B, A variables from (e.g. TOA radiance or reflectance) band combinations.
In any case, the server tile computation shall be changed in order to compute RGBA tiles from R, G, B, A variables.

**Describe alternatives you've considered**

The following tools are alternatives that may be of general interest as well (may create feature requests later):

* Compute data cubes that contain R, G, B, A variables e.g. using `xcube apply` CLI
* Precompute RGBA tile pyramids from data cubes

**Additional context**

Decided to be a must-have at DCS4COP IRM2 19.06.2019.

**Comment by AliceBalfanz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Finalize Demo Use Case for DCS4COP](https://trello.com/c/2WuYZeZh/76-finalize-demo-use-case-for-dcs4cop)

**Comment by AliceBalfanz** [comment]
this is already implemented, closing.
