### ISSUE TITLE
Extending help section after changing to click

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube#12]
The help section is incomplete, not showing the user the choice options to choose from at e.g. --proc. Needs to be added to general help section.

**Comment by AliceBalfanz** [comment]
This is implemented, however a different solution to integrate the help section might be better, e.g. by setting an epilog of a click command 
[http://click.palletsprojects.com/en/7.x/api/#click.Command](url)

**Comment by forman** [comment]
@AliceBalfanz, I believe we can close this one, as `xcube gen --info` does what is needed here. Or am I missing anything?
