### ISSUE TITLE
expand default processor of xcube-genl2 to handle  0-360 lon 

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube#13]
The default processor only accepts netcdf standard -180 to 180 longitudes and does not normalize input of longitude 0-360.

**Comment by forman** [comment]
See normalisation implementation  in Cate: https://github.com/CCI-Tools/cate/blob/master/cate/core/opimpl.py#L163

**Comment by forman** [comment]
Gunnar just pointed me to this cool function which you can use too: http://xarray.pydata.org/en/stable/generated/xarray.DataArray.roll.html

**Comment by forman** [comment]
@AliceBalfanz, for the current implementation, please note that

```
test/api/gen/default/test_gen.py::DefaultProcessTest::test_handle_360_lon
  D:\Projects\xcube\xcube\api\gen\default\iproc.py:183: FutureWarning: roll_coords will be set to False in the future. Explicitly set roll_coords to silence warning.
    dataset = dataset.roll(lon=lon_size_05)
```
