### ISSUE TITLE
Consolidate cubes to make them much faster

### ISSUE THREAD

**Issue by forman** [dcs4cop/xcube#141]
**Is your feature request related to a problem? Please describe.**

Opening larger cubes from OTC Object Storage or AWS S3 takes too long. Analysis has shown that this is caused mainly by the many HTTP requests made for 
* `.zarray` and `.zattrs` metadata files, either by checking for existence or to load them;
* time coordinate chunks if the chunking for time is one (e.g. `chunks={'time': 1, 'lat': 1000, 'lon': 1000)` . 

**Describe the solution you'd like**

"Consolidate" cubes after each append, insert, and overwrite of time slices using `xcube gen`. That includes 
1. calling zarr's [consolidate_metadata](https://zarr.readthedocs.io/en/stable/api/convenience.html#zarr.convenience.consolidate_metadata) function;
2. combine all time chunks into a single so time coordinate variable is never chunked.

TODO

- [x] a new CLI impl. module and public command `consolidate <dataset>` so we can consolidate existing cubes.
- [x] a new API impl. module and public function `consolidate_dataset` 
- [x] call `consolidate_dataset` from `xcube gen` after creating or extending cubes
- [x] in `xcube serve`, use xarray's [open_zarr](http://xarray.pydata.org/en/stable/generated/xarray.open_zarr.html) function with the `consolidated=True` flag.

**Additional context**

CyanoAlert cubes in OTC OBS take up to a few minutes to open, see #131 and https://github.com/dcs4cop/xcube-viewer/issues/61

**Comment by forman** [comment]
`consolidate` --> `optimze`

**Comment by forman** [comment]
@AliceBalfanz, @dzelge: I believe we may/should now remove `xcube prune` and instead make pruning an option of `xcube optimize`. What do you think?

**Comment by dzelge** [comment]
I think, that sounds right.

 

------------------------

Helge

Brockmann Consult

 

Von: Norman Fomferra <notifications@github.com> 
Gesendet: Montag, 12. August 2019 14:49
An: dcs4cop/xcube <xcube@noreply.github.com>
Cc: Helge Dzierzon <helge.dzierzon@brockmann-consult.de>; Mention <mention@noreply.github.com>
Betreff: Re: [dcs4cop/xcube] Consolidate cubes to make them much faster (#141)

 

@AliceBalfanz <https://github.com/AliceBalfanz> , @dzelge <https://github.com/dzelge> : I believe we may/should now remove xcube prune and instead make pruning an option of xcube optimize. What do you think?

**Comment by AliceBalfanz** [comment]
I agree.

**Comment by forman** [comment]
Done.

**Comment by forman** [comment]
Reopened, as xcube server does not yet support the consolidated flag.

**Comment by forman** [comment]
Done
