### ISSUE TITLE
Places not loading on PlaceGroupChange

### ISSUE THREAD

**Issue by dzelge** [dcs4cop/xcube#142]
**Describe the bug**

The place select stays empty when selecting place groups are selected.

**To Reproduce**
1. Go to cyanoalert
2. Click on select places and select a group
3. See places select

**Expected behavior**
Places should show up

**Comment by forman** [comment]
Does it happen with the demo configuration too?
Strange, this has been tested. See also unit-tests.

**Comment by AliceBalfanz** [comment]
Yes, with the demo configuration, the Places cannot be selected as well.

**Comment by dzelge** [comment]
HAve a look at the changes I have made. All relevant methods have not been called with load_features=True.

**Comment by dzelge** [comment]
This is teh URL in text that the xcube-viewer calls when attempting to fill the places:

https://cyanoalert.brockmann-consult.com/api/v1.dev/datasets/cyanoalert-olci-lswe-l2c-v1/places/Sweden_SE_Lakes
