### ISSUE TITLE
Make multi-resolution cubes work with object storage

### ISSUE THREAD

**Issue by forman** [dcs4cop/xcube#179]
**Is your feature request related to a problem? Please describe.**

Multi-resolution cubes (see `xcube level` command, `*.levels` directories) only work with the local file system. Most of our data cubes are stored in object storage, so we cannot configure `xcube serve` to work with them, which is the main use case.

**Describe the solution you'd like**

As with other `*.zarr` cubes, `*.levels` should work with object storage too. Implementation could be simplified by making the `*.levels` directory a valid zarr dataset, i.e. by just adding an empty `.zgroup` file.

**Comment by forman** [comment]
@AliceBalfanz, please test, it should work already, see code.

**Comment by AliceBalfanz** [comment]
There is code for it, but it is not working. I am debugging.

**Comment by forman** [comment]
I guess, we can close this?
