### ISSUE TITLE
Timeseries request - HTTP CORS Headers

### ISSUE THREAD

**Issue by JanssenBrm** [dcs4cop/xcube#187]
During the integration the xcube services into the EODataBee viewer (VITO), we are experiencing issues with regards to calling the TimeSeries services exposed  by the datacube.

In the application we are making requests to the following datacube endpoint:
_https://xcube2.dcs4cop.eu/dcs4cop-dev/api/0.1.0.dev6/ts/v1.1/ts/_

An example request is a POST request containing a geometry to the following endpoint:
_https://xcube2.dcs4cop.eu/dcs4cop-dev/api/0.1.0.dev6/ts/v1.1/ts/cmems_sst_ns_tirr_v1/analysed_sst/geometry?startDate=2015-01-01&endDate=2019-09-25_

However as we are making this request from a different domain (viewer.terrascope.be or dcs4cop.vgt.vito.be), we receive the following CORS errors:

_Access to XMLHttpRequest at 'https://xcube2.dcs4cop.eu/dcs4cop-dev/api/0.1.0.dev6/ts/v1.1/ts/cmems_sst_ns_tirr_v1/analysed_sst/geometry?startDate=2015-01-01&endDate=2019-09-25' from origin 'https://viewer.terrascope.be' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource._

As the error indicates the request is blocked because the server (in this case xcube2.dcs4cop.eu) did not include the _Access-Control-Allow-Origin_ header in the response request.

**Comment by forman** [comment]
@JanssenBrm, thanks! We'll have a look. We might make CORS-behavior configurable.

**Comment by forman** [comment]
Strange. Here are our defaults: https://github.com/dcs4cop/xcube/blob/master/xcube/webapi/service.py#L257-L263

**Comment by forman** [comment]
@dzelge, can you please have a look and help @JanssenBrm
