### ISSUE TITLE
False cube creation when output name is not set using xcube-genl2c

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube#19]
When the user does not set an output name for the generated data cube when using xcube-genl2c, the output is one output file per input files. This is because the default output name depends on the input file, which changes if there is more than one input file used for the cube generation. The default name should be set to a not changing name.

**Comment by forman** [comment]
@AliceBalfanz can you pls check, if this still applies?

**Comment by AliceBalfanz** [comment]
Yes, this still applies. For each input file a seperate output cube is created.
