### ISSUE TITLE
Data cubes should be optimized by default

### ISSUE THREAD

**Issue by forman** [dcs4cop/xcube#193]
**Is your feature request related to a problem? Please describe.**

xcube provides a couple of CLI and API functions that "optimize" xcube datasets e.g. pruning empty chunks, consolidating metadata, and un-chunking coordinate variables. The optimisation targets at remote datasets and achieves to minimise the number of HTTP requests and data to be fetched.

xcube currently wants users to explicitly use tools to create optimised data cubes. But since everyone wants optimised data cubes, the preferred way would be that all tools should generate optimised data cubes by default. For example, when  `xcube chunk` is applied to some optimal cube, the output will no longer be optimal. Instead, the user must apply the optimisation tools again. The goal is that `xcube chunk` should create an optimal dataset automatically.

An xcube dataset is optimal w.r.t. remote storage if

1. has a `.zmetadata` file in its root. This is the result of consolidating the root and all nested `.zattr` files. It will ensure that all the nested `.zattr` will no longer be requested from (remote) datasets.
2. has dimension-related coordinate variables that (a) are one-dimensional and (b) are composed of a single chunk. Dimension-related coordinate variables are read as index, having only one chunk means just one request on (remote) datasets for each dimension.
3. do **not** have chunk data files that solely comprise fill-values. This is an optional requirement. Note that the Zarr package detects missing chunks and fills them automatically without requesting data from (remote) datasets.

**Describe the solution you'd like**

CLI/API functions that output an *xcube dataset* should auto-optimize it.

CLI/API functions may have an option to disable individual auto-optimizations, e.g. for performance reasons.

CLI/API functions that read xcube datasets should raise a warning, if a dataset does not conform with the expected optimisations, e.g. `warning: dimension-related coordinates should not be chunked` and similar (see #176).

Change the [xcube Dataset Specification](https://github.com/dcs4cop/xcube/blob/master/docs/source/cubespec.md) to reflect the structure of an xcube dataset optimized for remote storage.

**Comment by AliceBalfanz** [comment]
This has been adressed by https://github.com/dcs4cop/xcube/pull/274
