### ISSUE TITLE
xcube gen performs inaccurate reprojection (tbc)

### ISSUE THREAD

**Issue by forman** [dcs4cop/xcube#206]
From diverse investigations it turned out that the shift of cells as seen in https://github.com/dcs4cop/xcube-viewer/issues/64 may probably originate from innaccurate reprojection in `xcube gen` tool.

A first idea is to parameterise `xcube gen` to perform a reprojection with more ground control points so we perform a quantitative anaylsis.

**Comment by AliceBalfanz** [comment]
One reason of the shift is that the reprojection of the data set is performed on the whole extent of the input file. Part avoiding the shift would be to first make a subset of the area and then perform the reprojection. Furthermore one xcube dataset should not cover a very large area. If an area of interest is large, the solution might be to produce several xcube datasets which then are combined via the server/viewer to appear as one data set.

**Comment by forman** [comment]
Inaccuracy isn't a bug.

**Comment by forman** [comment]
Fixed by new rectification
