### ISSUE TITLE
 xcube/xcube/core/gen/gen.py - issue in the last update

### ISSUE THREAD

**Issue by joaofelipecsantos** [dcs4cop/xcube#225]
**Describe the bug**
Error to read the line 357 at xcube/xcube/core/gen/gen.py 

**To Reproduce**
1. Info about my data.
- I have netCDF data with:
  - coords = (lat, lon)
  - var = CHL
- These data have inside them the Global Attributes with:
  - **time_coverage_start** and time_coverage_end** (format %Y-%m-%dT%H%M%S).
  - The **time_coverage_start** and time_coverage_end** are strings.

Yesterday I ingested these data to a cube without errors.
Today I update the xcube before continue and I received an error saying that at line 357 in the file "xcube/xcube/core/gen/gen.py" was not possible to find the attribute **time**.

2. Changes that I did in  xcube/xcube/core/gen/gen.py 
- If you open the gen.py file you can see what is in the figure below:
![ticket03_01](https://user-images.githubusercontent.com/32440152/68469040-9d9d6f80-0219-11ea-8373-ef41e4adc52b.png)

- I changed the line 357 to:
`time_stamp = pd.to_datetime(dataset.time_coverage_start, utc=True)`

**Now my `xcube gen ...` is working again.**

**Expected behavior**
The `xcube gen ...` options should accept as attributes 'time' and also 'time_coverage_start' or 'time_start' (this last one is how BC Global Attributes called the date and time).

**Screenshots**
Above.

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 18.04 LTS
 - Version: xcube version last update on 08/11/2019.

**Additional context**
None.

**Comment by AliceBalfanz** [comment]
Hi Joao, 

yes, I am sorry for not having tested the new addiditon completly. An update will follow either today or on Monday.  Then the input processors will be updated as well, so you will have to pull the changes from them as well. (There is already a pull request for xcube, but the PRs for the input processors are not ready yet.) 
Sorry, that you are experiencing these issues! 
Best, 
Alicja

**Comment by AliceBalfanz** [comment]
closed by PR #223
