### ISSUE TITLE
New naming of data cube types

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube#23]
The naming of the data cube levels should give better indication of the type. One type of a generated cube is spatial regular with original time stamps, therefore temporal irregular. The second type is both, spatially and temporally regular. At the moment the naming of the types is too similar to data processing levels in earth observation.

Existing propositions are the addition of 'tirr' for time irregular and 'treg' for time regular. 

Following the naming decision, the code and documentation needs to be adjusted.

**Comment by forman** [comment]
Not software-related.
