### ISSUE TITLE
Demodatasets in OBS

### ISSUE THREAD

**Issue by dzelge** [dcs4cop/xcube#243]
**Is your feature request related to a problem? Please describe.**

The xarray release archive is fairly big (50MBs). This is due to example data that are included in the
package (56MBs unzipped). I would, therefore, like to suggest storing demo data in an OBS and enable the user listing and loading these data similar to seaborn:

```
import seaborn as sns
tips = sns.load_dataset("tips")
```

**Describe the solution you'd like**

Add a core function that loads and lists demo data from an OBS:

```
list_demodata()
load_demodata(data_name: str) -> xarray.Dataset
```

**Comment by forman** [comment]
Isn't this an xarray issue?

**Comment by dzelge** [comment]
Not necessarily. because I am speaking about specific xcube demo datasets e.g. `xcube/examples/serve/demo/`. Nothing to do with xarray.

**Comment by AliceBalfanz** [comment]
This issue is stale, closing.
