### ISSUE TITLE
Timeseries Internal Server Error: ValueError: the first argument to .drop must be a dictionary

### ISSUE THREAD

**Issue by digitaltopo** [dcs4cop/xcube#244]
**Describe the bug**
While testing the [Web API and Server](https://xcube.readthedocs.io/en/latest/webapi.html) locally, I am seeing the following error for [time series request](https://app.swaggerhub.com/apis-docs/bcdev/xcube-server/0.2.0#/time-series/getTimeSeriesForPoint) for a point: `GET:  http://localhost:8080/ts/local_ts/conc_chl/point?lon=2&lat=50`

```
{
    "error": {
    "code": 500,
    "message": "Internal Server Error",
    "traceback": [
        "Traceback (most recent call last):\n",
        "  File \"/path/to/env/lib/python3.7/site-packages/tornado/web.py\", line 1699, in _execute\n    result = await result\n",
        "  File \"/path/to/env/lib/python3.7/site-packages/xcube/webapi/handlers.py\", line 476, in get\n    max_valids)\n",
        "  File \"/path/to/env/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n    result = self.fn(*self.args, **self.kwargs)\n",
        "  File \"/path/to/env/lib/python3.7/site-packages/xcube/webapi/controllers/time_series.py\", line 99, in get_time_series_for_point\n    max_valids=max_valids)\n",
        "  File \"/path/to/env/lib/python3.7/site-packages/xcube/webapi/controllers/time_series.py\", line 244, in _get_time_series_for_point\n    ts_ds = ts.get_time_series(dataset, point, var_names, start_date=start_date, end_date=end_date)\n",
        "  File \"/path/to/env/lib/python3.7/site-packages/xcube/api/ts.py\", line 81, in get_time_series\n    dataset = select_vars(cube, var_names)\n",
        "  File \"/path/to/env/lib/python3.7/site-packages/xcube/api/select.py\", line 19, in select_vars\n    return dataset.drop(dropped_variables)\n",
        "  File \"/path/to/env/lib/python3.7/site-packages/xarray/core/dataset.py\", line 3643, in drop\n    return self.drop_sel(labels, errors=errors)\n",
        "  File \"/path/to/env/lib/python3.7/site-packages/xarray/core/dataset.py\", line 3689, in drop_sel\n    labels = either_dict_or_kwargs(labels, labels_kwargs, \"drop\")\n",
        "  File \"/path/to/env/lib/python3.7/site-packages/xarray/core/utils.py\", line 257, in either_dict_or_kwargs\n    \"the first argument to .%s must be a dictionary\" % func_name\n",
        "ValueError: the first argument to .drop must be a dictionary\n"
        ]
    }
}
```

The same happens on every other variable and with other datasets from the demo directory. I did not however have this issue with other deployed servers, ex) https://xcube2.dcs4cop.eu/dcs4cop-dev/api/latest/ts/cmems_sst_ns_tirr_v1/analysed_sst/point?lon=10&lat=50

Of course this also effects the the [deployed viewer demo app](https://xcube-viewer.s3.eu-central-1.amazonaws.com/index.html), when using the local server I am running, although due to [another bug](https://github.com/dcs4cop/xcube-viewer/issues/100), I haven't been able to test this functionality on the viewer with other datasets. (Although the viewer issue is expected here as it's calling the api)

Is there an issue with the way I'm requesting this time series data? 

**To Reproduce**
1. Install xcube `conda install -c conda-forge xcube`
2. Clone xcube `git clone git@github.com:dcs4cop/xcube.git`
3. Serve xcube from project directory: `xcube serve --port 8080 --config ./examples/serve/demo/config.yml --verbose`
4. Access `ts` endpoint: `http://localhost:8080/ts/local_ts/conc_chl/point?lat=50&lon=2`

**Expected behavior**
See a [timeseries response](https://app.swaggerhub.com/apis-docs/bcdev/xcube-server/0.2.0#/time-series/getTimeSeriesForPoint)

**Desktop:**
 - OS: Ubuntu
 - Browser: Chromium

**Comment by AliceBalfanz** [comment]
Hi digitaltopo, 
since you seem to use git clone to build xcube from sources:
my guess would be, that you have an existing xcube environment from a prior version. 
In that case, please do the following steps: 
1. go to the directory, where you have xcube 
2. Being in the directory do `conda env update -n xcube --file environment.yml  --prune` via the command line
3. `conda activate xcube`
4. `python setup.py develop`
5. `xcube serve --port 8080 --config ./examples/serve/demo/config.yml --verbose`

Does this help?

**Comment by forman** [comment]
@digitaltopo, if you already have an `xcube` environment, you'll need to update it for the current master branch, as we now require `xarray > 0.14`.

    $ cd xcube
    $ conda env update

**Comment by forman** [comment]
Oops, as @AliceBalfanz wrote...

**Comment by forman** [comment]
@digitaltopo, this one can be closed, right?
