### ISSUE TITLE
Problem generating tiles for cubes with ascending latitudes

### ISSUE THREAD

**Issue by rabaneda** [dcs4cop/xcube#251]
After creating my own Sentinel-1 datacube and trying to use the xcube viewer, I found the following problem:

Coordinate values must have a descending order for latitude, and ascending order for longitude. A datacube could have different coordinate values order and still be a correct input or datacube. However, if that is the case, the xcube viewer will not plot the data on the map (even when the time graph works properly). There are two ways of solving this, adapting the viewer to be able of plotting the data whatever is the coordinate values order, or add this few lines to xcube verify. 

I had done a pull request with the new lines, as a fork file. Unfortunately, I don't something wrong because all checks failed. Perhaps it is necessary to have write access. But if you go to the pull request you'll see the new lines I added to verify.py

**Comment by forman** [comment]
@rabaneda, thanks for looking into this.

> Coordinate values must have a descending order for latitude, and ascending order for longitude.

That shouldn't be true in xcube. Latitude coordinates may be ascending or descending, and there are many places in the code that consider the order.

> However, if that is the case, the xcube viewer will not plot the data on the map (even when the time graph works properly). There are two ways of solving this, adapting the viewer to be able of plotting the data whatever is the coordinate values order, or add this few lines to xcube verify.

Definitely adapting the viewer to be able of plotting the data. Please rename this issue or create a new one. Your changes to `xcube verify` do not reflect xcube's intention to deal with both latitude orders.

**Comment by rabaneda** [comment]
@forman, I'm thinking to close this issue, and reopen it on xcube viewer unless you tell me that it has been already addressed. In that case, I'll just close the issue.

**Comment by forman** [comment]
@rabaneda, it is fine, I'm renaming this one.

**Comment by forman** [comment]
@rabaneda This should be fixed now on `master` branch.
