### ISSUE TITLE
Include `xcube prune` included into `xcube gen`

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube#268]
**Is your feature request related to a problem? Please describe.**
When generating a xcube dataset one has to do  `xcube prune` every time a datacube is completed or even if a time slice is added to an existing, pruned datacube. This is an extra manual step to do before publishing datacubes - therefore it would be nice to have `xcube prune` integrated into `xcube gen`. 

**Describe the solution you'd like**
In `xcube gen`, before appending a time slice to a xcube dataset  empty chunks should already be deleted and not written to disk. 

**Describe alternatives you've considered**
Keeping on executing `xcube prune` manualy.

**Comment by forman** [comment]
1. I don't understand the title of this issue.
2. This is a duplicate or detail of #193

**Comment by AliceBalfanz** [comment]
@forman: You are right. Sorry about that!
