### ISSUE TITLE
Time-series perfomance drop

### ISSUE THREAD

**Issue by forman** [dcs4cop/xcube#299]
**Describe the bug**

Time-series extraction via the web API in released version 0.4 now obviously takes much longer than in 0.3.

**To Reproduce**

With both versions:

- Run server with long term cube
- Start viewer
- Place point to create time series

**Comment by nyoudjou** [comment]
- I checked with both versions (0.4.0 and 0.3.0) for the same dataset,  at same location and variable,  I get the same performance issue  ~20min.
- with the direct access using python script in jupyter notebook:
    - without rechuncking: 11s
    - with new rechunck: 0.4s
