### ISSUE TITLE
xcube gen sorts input list and therefore might append wrong time order

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube#33]
The order of the appending step of input files to the cube is relevant. 
When having input data which has input names first differentiated by e.g. A and B, the input files are sorted by these characters instead of the time stamp. When submitting a list of input files, which is already sorted by time tamp, omitting the characters A and B xcube gen sorts the list internally and creates a wrong cube, first appending all input data with A and then with B.  

**Expected behavior**
xcube gen should not sort again the input files. It should take the order given by the user.

**Comment by forman** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Generate S2-Plus data cubes for generic use case](https://trello.com/c/OGLyedMK/2-generate-s2-plus-data-cubes-for-generic-use-case)

**Comment by AliceBalfanz** [comment]
already implemented and merged into master. Can be used with parameter --sort when input data list should be sorted by xcube gen
