### ISSUE TITLE
Leverage rechunker package for rechunking?

### ISSUE THREAD

**Issue by rabernat** [dcs4cop/xcube#335]
Xcube recently popped back on to my radar. It's fantastic to see how this project has matured--it looks extremely for those wishing to leverage the xarray / dask / zarr software stack without having to write python code. We are currently discussing it on the [Pangeo Forum](https://discourse.pangeo.io/t/data-cubes-discussion-once-more-ever-heard-of-xcube/851) with great enthusiasm. We (Pangeo project) would love to help with xcube however we can.

In reading your docs, I noticed you have some rechunking capabilities built into xcube. I thought you might be interested in [rechunker](https://rechunker.readthedocs.io/en/latest/), a new package designed for on-disk rechunking. This package solves some of the computational bottlenecks related to dask's internal implementation of rechunking. (See also [blog post](https://medium.com/pangeo/rechunker-the-missing-link-for-chunked-array-analytics-5b2359e9dc11).)

Congratulations on all your hard work and progress on this great tool. 🥇

**Comment by forman** [comment]
Hi @rabernat! 

> We (Pangeo project) would love to help with xcube however we can.
Wow, fantastic, thanks for the offer! The team would be very happy if we could meet soon. We would explain to you the xcube context, why we made it, how it is used. By bringing up the major challenges we are facing we could identify how to collaborate.

> I thought you might be interested in rechunker,
Indeed, thanks for the hint!

- Norman
