### ISSUE TITLE
Rename input processor to input transformer

### ISSUE THREAD

**Issue by forman** [dcs4cop/xcube#34]
The term "input processor" is confusing for EO-scientists as it makes them believe, some thematic EO data products are generated in this step. 

It has been agreed, the term "input transformer" better describes the nature of this components, namely to prepare a (L1 or L2 EO data file) input for appending it to a data cube, which usually requires time stamp identification, variable selection, masking, and reprojection of data to target SRS.

Therefore

- [ ] rename class `InputProcessor` to `InputTransformer`
- [ ] rename its method `process` to `transform`
- [ ] rename configuration parameter `input_proc` to `input_transformer` in API and CLI
- [ ] adjust API and CLI docs

**Comment by AliceBalfanz** [comment]
To many other, more important stuff to do
