### ISSUE TITLE
xcube's MultiLevelDataset to be compatible with xarray's Dataset interface

### ISSUE THREAD

**Issue by forman** [dcs4cop/xcube#350]
**Is your feature request related to a problem? Please describe.**

`xcube.core.mldataset.MultiLevelDataset` represents an `xarray.Dataset` at multiple spatial resolutions (image pyramid). The name implies it should be a _Dataset_, however its interface is _not_ compatible with `xarray.Dataset` :

```typescript
interface MultiLevelDataset {
    num_levels: int;
    get_dataset(level: int) => xarray.Dataset[];
    base_dataset: xarray.Dataset;
    ...
}
```

**Describe the solution you'd like**

```typescript
interface MultiLevelDataset extends xarray.Dataset {
    num_levels: int;
    get_dataset(level: int) => xarray.Dataset[];
    base_dataset: xarray.Dataset;
    ...
}
```

where the `base_dataset`'s default implementation should simply return (it)self.

**Additional context**

xcube's new data store framework allows passing a `type_id` paramjeters that comprises a type name and "flags" that add further criteria to the desired type. To request a multi-resolution data cube from a data store, we'd like to use the store like so:

```
ml_dataset = store.open_data(type_id="dataset[cube,multilevel]", **open_params)
```

See also PR #339.

**Comment by forman** [comment]
I see a fundamental problem with my approach described above: Actually, all methods of `xarray.Dataset` that return a `xarray.Dataset` should be overridden to return instances of `MultiLevelDataset`.

(And actually, then there should also be `MultiLevelDataArray` that are multi-resolution versions of `xarray.DataArray`.)

**Comment by TonioF** [comment]
I agree. The result of to_array() called on a MultiLevelDataset should be a MultiLevelArray.

**Comment by forman** [comment]
Do not derive from `xr.Dataset` or `xr.DataArray`. Instead implement `xr.Dataset` or `xr.DataArray accessors for multi-level datasets, see http://xarray.pydata.org/en/stable/internals/extending-xarray.html
