### ISSUE TITLE
Adapt DataStore Interface to fully support TypeSpecifiers

### ISSUE THREAD

**Issue by TonioF** [dcs4cop/xcube#352]
After having introduced the TypeId class, we found that the current DataStore interface is not sufficient to fully support the differentiations made possible with the TypeId. We also found that the term TypeId is not optimal, therefore we will change it to TypeSpecifier.
Changes:

- [x] TypeId -> TypeSpecifier
- [x] New method: get_type_specifiers_for_data(self, data_id: str)
- [x] get_data_ids(self, type_id: str = None)   ->  get_data_ids(self, type_specifier: str = None, include_titles = True)
- [x] has_data(self, data_id: str)   ->  has_data(self, data_id: str, type_id: str = None)
- [x] describe_data(self, data_id: str, type_id: str = None)  ->  describe_data(self, data_id: str, type_id: str = None)
- [x] get_search_params_schema(cls)  ->  get_search_params_schema(cls, type_id: str = None)

These interface changes need to be considered by all store implementations; the ones contained in xcube and the others which are maintained as plugin.

**Comment by forman** [comment]
Done!
