### ISSUE TITLE
Reprojection test failing with GDAL 3.1

### ISSUE THREAD

**Issue by pont-us** [dcs4cop/xcube#375]
With any version of the `gdal` package from 3.1.0 onwards, [`test_reproject_crs_to_wgs84_s2plus`](https://github.com/dcs4cop/xcube/blob/79e01b7859bdd170bf358ce954a24812eb72b68c/test/core/test_reproject.py#L14) fails. gdal 3.1.0 was released half a year ago, but this bug never surfaced because xcube was specifying `proj4` rather than `proj` for the PROJ package (see Issue #374), which seems to have indirectly restricted `gdal` to <3.1 (by some chain of dependencies that I haven't fully worked out). The test failure comes from the array equality assertion in the final line:

```
x and y nan location mismatch:
 x: array([[0.025002, 0.019001, 0.019001, 0.008999, 0.012001, 0.012001],
       [0.028   , 0.021   , 0.021   , 0.009998, 0.008999, 0.008999],
       [0.036999, 0.022999, 0.022999, 0.007   , 0.009998, 0.009998],...
 y: array([[nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan]], dtype=float32)
```

The reprojection returns an array consisting entirely of NaN values. Results of some further investigation:

 - The test fails with gdal 3.1.0, but passes with gdal 3.0.4 (the previous release).
 - The test performs the reprojection with a call to `xcube.core.reproject.reproject_crs_to_wgs84`, which in turn
   calls `gdal.ReprojectImage`.
 - The test uses the default resampling algorithm (`Nearest`), but fails in the same way if `Bilinear` or `Cubic` is used.
 - The `gdal.ReprojectImage` call does not return an error code or throw an exception, and monitoring GDAL warnings (as described [here](https://gis.stackexchange.com/a/68042/)) does not produce any additional diagnostic output.
 - The `nan` values are there because `nan` has been specified as the `NO_DATA` value for the destination array. Changing `NO_DATA` to another value in `reproject_crs_to_wgs84` produces an array filled with that value instead.
 - `gdal.ReprojectImage` calls [`GDALReprojectImage`](https://github.com/OSGeo/gdal/blob/0941b0f7aaa5bff5fd12a6fed03d4e385c4dcae4/gdal/alg/gdalwarper.cpp#L56) in the GDAL C++ library, which makes use of [`GDALWarpOperation`](https://github.com/OSGeo/gdal/blob/8eb82570b7c8bca96951b923412e0d3acdc152f9/gdal/alg/gdalwarpoperation.cpp#L93).
 - The [GDAL changelog](https://github.com/OSGeo/gdal/blob/80e76864400808e07881b43469d4808a52858fe4/gdal/NEWS#L666) for the 3.1.0 release lists a number of changes to reprojection and warping code. Presumably one of these is responsible for the changed behaviour.

**Comment by pont-us** [comment]
Related: Issue #348 .

**Comment by StefanBrand** [comment]
I can give some background on the GDAL/PROJ version dependencies. The latest version of the legacy [`proj4`](https://anaconda.org/conda-forge/proj4) package in `conda-forge` is PROJ 6.1.1. GDAL 3.1 depends on PROJ 7, which is only available in the [`proj`](https://anaconda.org/conda-forge/proj) package on `conda-forge`.

When I try to create a `conda env`, this is part of the conflicts:

```
Package proj conflicts for:
proj=6
gdal=3.1 -> libgdal==3.1.4=h744752d_4 -> proj[version='>=7.0.0,<7.0.1.0a0|>=7.1.0,<7.1.1.0a0|>=7.1.1,<7.1.2.0a0|>=7.2.0,<7.2.1.0a0']
```

**Comment by forman** [comment]
No longer applicable. Removed test, function was unused. We have beter alternatives now (rectification).
