### ISSUE TITLE
Add a "--csv" (or similar) option to "xcube io dump"

### ISSUE THREAD

**Issue by pont-us** [dcs4cop/xcube#388]
**Is your feature request related to a problem? Please describe.**

Problem: there is no way to make xcube produce a concise summary of the available stores and datasets. At present the store details can be exported using `xcube io dump`, but this produces a very large and detailed JSON file which requires post-processing to create a readable summary.

**Describe the solution you'd like**

`xcube io dump` should have an option to produce a CSV or Excel summary in addition to, or instead of, the JSON output. Sketch of the interface:

 `xcube io dump --summarize-as csv --summarize-to filename.csv --no-json` : write a summary in CSV format to the file `filename.csv`, and do not write the usual JSON output file.

`xcube io dump --summarize-from store-dump.json --summarize-as excel --summarize-to filename.xls` : write a summary in Excel format, based on the previously dumped JSON file `store-dump.json` rather than the currently available stores and datasets.

There should also be options to control which fields are included in the summary.

**Describe alternatives you've considered**
Currently, the JSON output from `xcube io dump` can be postprocessed using separate, ad-hoc scripts written by the user.

**Comment by gunbra32** [comment]
I would make the columns to be integrated in the summary configurable via a kwarg with a dictionary.

**Comment by forman** [comment]
I believe, this part of your desired solution is overengineered: `xcube io dump --summarize-from store-dump.json --summarize-as excel --summarize-to filename.xls`. 

Once we have a CSV we can go with other tools, This is not xcube's domain. Remember, xcube is a _data cube_ toolkit.
