### ISSUE TITLE
Unittest test_fetch_wmts_kvp_tile does not pass anymore

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube#396]
**Describe the bug**
Unittest test_fetch_wmts_kvp_tile does not pass anymore. The error message is `Illegal format 'image/png'`

See:
https://ci.appveyor.com/project/bcdev/xcube/builds/37132711/job/a5oatfkbfhs4oimk#L2400

**Comment by pont-us** [comment]
The test failure seems to have appeared in commit 889d3e839.
