### ISSUE TITLE
xcube.core.extract.get_cube_values_for_points() - Dataset is not a valid xcube dataset

### ISSUE THREAD

**Issue by iliasioannou** [dcs4cop/xcube#434]
Related to #104

The function for extracting values returns always an error

`xcube.core.extract.get_cube_values_for_points(XCube, Dictionary)`

Where: `Dictionary= dict( time='2019-03-01', lat='30.',lon='36.', method='nearest')`

The error is:
> ValueError: Dataset is not a valid xcube dataset, because:
> - coordinate variable 'lon' is not equidistant;
> - coordinate variable 'lat' is not equidistant.

What does that error mean? (or better - How should the dictionary be implemented?)

**Comment by forman** [comment]
It means that the deltas between two subsequent `lon` (or `lat`) array values is not the same constant number over all such deltas. This is a data cube assertion that is veryfied by xcube on the first `cube: xr.Dataset` function argument. 

You can try getting around that assertion by passing `cube_asserted=False`.

**Comment by forman** [comment]
If the second `points` argument of the `get_cube_values_for_points` is a dictionary, as it is the case in your example, its keys must be dimension names / names of coordinate variables in the dataset passed as first `cube` argument. The dictionary values must be arrays all having the same length. 

Therefore your dictionary 

> Where: Dictionary= dict( time='2019-03-01', lat='30.',lon='36.', method='nearest')

is not valid. I assume you pass `method` here to use nearest neighbour indexing. Do not include `method` in the `points` dictionary. Instead do it like so:

```python
xcube.core.extract.get_cube_values_for_points(XCube, Dictionary, method="nearest")
```

**Comment by iliasioannou** [comment]
`aDict = dict(time=['2019-03-01'], lat=[30.],lon=[36.])`
 
Gives this as output. 
> {'time': ['2019-03-01'], 'lat': [30.0], 'lon': [36.0]}

Then  i execute 
`xcube.core.extract.get_cube_values_for_points(MedSea, aDict, method='nearest', cube_asserted=False)`
but it still gives the same error. 


-

1. Can it be CRS related?
2. I do not really understand this " It means that the deltas between two subsequent lon (or lat) array values is not the same constant number over all such deltas. " Can you point to some doc/explanation?

**Comment by iliasioannou** [comment]
I wasn't able to use the above function (_get_cube_values_for_points_) .

The following line outputs a CSV with Chlorophyll values, according to the specified coordinates and time range.
`MedSea.CHL.sel(time=slice('2019-01-01', '2020-06-22')).sel(lat=44.0, lon=34.0, method='nearest').to_pandas().to_csv()`

**Comment by forman** [comment]
> On the other hand if i pass **cube_asserted = True** , it gives the following error.
> 
> ```AttributeError: 'list' object has no attribute 'shape'```

I agree, that is confusing. Please pass numpy arrays, not lists. We'll change the method to accept lists and tuples too.

**Comment by forman** [comment]
> `MedSea.CHL.sel(time=slice('2019-01-01', '2020-06-22')).sel(lat=44.0, lon=34.0, method='nearest').to_pandas().to_csv()`

Of course, that works too. The xcube function has been optimized for the case when you pass a very long list of `points`.
