### ISSUE TITLE
Extract values from xcube

### ISSUE THREAD

**Issue by iliasioannou** [dcs4cop/xcube#435]
Hello.
I have a Cube with 3 dimensions (time, lat , lon) and as data variables the values of CHL.

![image](https://user-images.githubusercontent.com/3886244/115584295-f99f6b00-a2ca-11eb-8663-a72da0eeeb57.png)

I want to extract the CHL values from the cube, given a point (lat,lon) and a range of days.

What is the most simple way to that?

**Comment by gunbra32** [comment]
![grafik](https://user-images.githubusercontent.com/7138923/115672253-ab7e7c00-a34b-11eb-985f-4cdf4351a356.png)

**Comment by iliasioannou** [comment]
@gunbra32 Thanks , but this operation selects values of CHL for a point. 
What if i want to filter the values according to a temporal range?

e.g. Given (lat,lon), what are the daily CHL values from 2021/01/01 to 2021/02/01?

**Comment by gunbra32** [comment]
Very similar. Please refer to the xarray [documentation ](http://xarray.pydata.org/en/stable/index.html) for generic xarray functionality. There you find plenty of hands-on examples on handling data sets. 
![image](https://user-images.githubusercontent.com/7138923/115717951-f82d7b80-a37a-11eb-96b6-89a4d9e63d16.png)

**Comment by iliasioannou** [comment]
Thanks that works just fine.  I also appreciate the tip about Xarray.
