### ISSUE TITLE
S3 and Directory Store do not recognize data ids

### ISSUE THREAD

**Issue by TonioF** [dcs4cop/xcube#450]
When the write_data method of the directory store or the s3 store is called with a data_id parameter, it is not checked whether this parameter is valid, i.e., whether it has a valid extension. It is simply used. In consequence, when the data is written, it might happen that the store writes the data, but when the dataset later is accessed (by, e.g., has_data), it cannot be found.

A store shall always be able to correctly interpret a data id that it has returned itself. To achieve this, either the store must be able to interpret data ids from which the data type can not be immediately guessed or extend the id with the according file extension.

**Comment by forman** [comment]
We use extensions
