### ISSUE TITLE
Provide xcube documentation

### ISSUE THREAD

**Issue by forman** [dcs4cop/xcube#46]
- [ ] Setup Sphinx doc gen
- [ ] Setup ReadTheDocs build
- [ ] Write actual docs with focus on `xcube gen` and `xcube serve`

**Comment by forman** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Write xcube user documentation](https://trello.com/c/urOTMy94/13-write-xcube-user-documentation)

**Comment by AliceBalfanz** [comment]
Take a look in the Cate project.

**Comment by forman** [comment]
Closed for 0.2. Reopen on doc updates.
