### ISSUE TITLE
Pangeo Showcase talk on Xcube goals, current capabilities and roadmap?

### ISSUE THREAD

**Issue by rsignell-usgs** [dcs4cop/xcube#464]
It would be great to get a presentation on Xcube as part of the [Pangeo Showcase](https://pangeo.io/pangeo-showcase.html) series, a weekly webinar the highlights cool activities taking place in the scalable scientific python ecosystem!

If someone is interested in giving a 15 min talk some time in the future, please fill out this [short google form](https://docs.google.com/forms/d/e/1FAIpQLSddb5s_nM5So48mTk1SkTxRPKfE0fvdx73ZsyAt--v87BK3vw/viewform) or ping me here or on https://gitter.im/rsignell-usgs/community for more info. 

Thanks for the consideration!

**Comment by forman** [comment]
Hi @rsignell-usgs, thanks for considering us! Please note that we not (yet) use Pangeo, however we depend on the same package stack.

**Comment by rsignell-usgs** [comment]
@forman, Pangeo is really just an open community with a shared vision of scalable, flexible and open processing systems. 
I think xcube would be perfect!   Would someone be interested in sharing your vision and progress with us?

**Comment by rsignell-usgs** [comment]
@forman, woohoo!  Looking forward to it!

**Comment by rsignell-usgs** [comment]
@forman are you guys ready to give a 15 min talk on Xcube to the Pangeo Showcase series?

**Comment by rsignell-usgs** [comment]
@forman we have next week open!   😸

**Comment by AliceBalfanz** [comment]
Closing, because Showcase Talk is today: https://pangeo.io/pangeo-showcase.html  :)
