### ISSUE TITLE
xcube gen to accept a text file with file names as input

### ISSUE THREAD

**Issue by gunbra32** [dcs4cop/xcube#47]
**Is your feature request related to a problem? Please describe.**
related to #33 

**Describe the solution you'd like**
Users shall have the possibility to provide the files sorted in the correct order in a text file if a simple sorting by file names would lead to a wrongly ordered cube. 

**Describe alternatives you've considered**
Rather than leaving it to the user to provide a correctly sorted file list, xcube gen could check if t+1>t before appending time slice to cube. And if needed re-arrange the cube.

**Comment by AliceBalfanz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Generate S2-Plus data cubes for generic use case](https://trello.com/c/OGLyedMK/2-generate-s2-plus-data-cubes-for-generic-use-case)
