### ISSUE TITLE
Three ExtractCliTest unit tests failing

### ISSUE THREAD

**Issue by pont-us** [dcs4cop/xcube#472]
**Describe the bug**

Running the test suite with the current master produces (amongst others) the following failures.

```
FAILED test/cli/test_extract.py::ExtractCliTest::test_all_invalid_points - Va...
FAILED test/cli/test_extract.py::ExtractCliTest::test_extract_points_with_refs
FAILED test/cli/test_extract.py::ExtractCliTest::test_some_invalid_points - V...
```

In all cases, the error is "ValueError: Index idx invalid", raised during [this call](https://github.com/dcs4cop/xcube/blob/ae23cf0cdbad992f303706f50044e1c058c02c88/test/cli/test_extract.py#L88) to `pandas.read_csv`. Pandas is looking for a column titled, `idx`, but `xcube extract ... --refs` omits this column header, as I verified manually:

```
$ xcube extract examples/serve/demo/cube.nc test/cli/extract-points/all-invalid-points.csv --refs
,quality_flags,kd489,conc_tsm,conc_chl,c2rcc_flags,id_ref,lat_ref,lon_ref,time_ref
0,,,,,,0,51.5,2.0,2017-01-16T08:00:00Z
1,,,,,,1,51.5,2.1,2017-01-16T08:00:00Z
2,,,,,,2,51.5,2.2,2017-01-16T08:00:00Z
3,,,,,,3,51.5,2.3,2017-02-01T12:00:00Z
4,,,,,,4,51.5,2.4,2017-02-01T12:00:00Z
5,,,,,,5,51.5,2.5,2017-02-01T12:00:00Z
```

**To Reproduce**
1. Create / ensure a current xcube conda environment with latest conda-forge package versions.
2. Check out latest master commit of xcube.
3. Execute `pytest -k test_extract`

**Expected behavior**
The `test_extract` tests all pass.

**Desktop (please complete the following information):**
 - Browser n/a
 - Version: commit ae23cf0cdb

**Additional context**
From the CI build logs, it seems that these tests starting failing on 2021-05-20, between commits c317afed and 3072dfff (on different branches). In the CI history, last working and first non-working commits on master are b2b9d53b and 62bf2000 respectively. It appears that the cause is a change in a dependency, since the tests also fail in a freshly-created environment with xcube release 0.8.1 (which, of course, passed all tests when it was released).

Dependency version diffs between commits c317afed and 3072dfff:
 - markupsafe 2.0.0 -> 2.0.1
 - numpy 1.20.2 -> 1.20.3
 - python 3.9.4 -> 3.9.5
 - xarray 0.18.0 -> 0.18.2
 - xorg-libx11 1.7.0 -> 1.7.1

Downgrading xcube to 0.18.0 in my environment makes the tests pass, so it seems that the 0.18.0 -> 0.18.2 update is what broke them.

**Comment by forman** [comment]
Fixed
