### ISSUE TITLE
non standard WMTS Tile API?

### ISSUE THREAD

**Issue by tiagoams** [dcs4cop/xcube#476]
The WMTS Tile API in xcube is:

/wmts/**1.0.0**/**tile**/{dataset}/{variable}/{z}/{y}/{x}.png

When trying to access WMTS from QGIS or ARCGIS Pro [the expected API seems to be](https://developers.arcgis.com/rest/services-reference/enterprise/wmts-tile-map-service-.htm):

    https://<wmts-url>/tile/<wmts-version>/<layer>/<style>/<tilematrixset>/<tilematrix>/<tilerow>/<tilecol>.<format>

Note that the version and tile are swapped around. I can't find in the OGC website what the actual standard says about this, but maybe this is non-standard, and might be causing the problem below.

To replicate:
When importing xcube WMTS into QGIS 3.14 I define the service as:

https://datacube.cefas.co.uk/xcube/wmts/1.0.0/WMTSCapabilities.xml

The discovery works, listing the layers, but hangs trying to render.

On ARCGIS Pro it refses the url as invalid WMTS.

xcube 0.8.1

**Comment by forman** [comment]
Hi @tiagoams!

> I can't find in the OGC website what the actual standard says about this, but maybe this is non-standard, and might be causing the problem below.

Right, this is not standardized. However, a WMTS must make use of _URL templates_ which have standardized template variables. You can find the WMTS tile URL templates for layers in the `GetCapabilities` response of any WMTS server. It is contained in the `ResourceURL` element of a laye. For example:

    $ curl https://datacube.cefas.co.uk/xcube/wmts/1.0.0/WMTSCapabilities.xml | grep ResourceURL
  
Therefore I do not believe that this causes the problems you see.

> The discovery works, listing the layers, but hangs trying to render.
> On ARCGIS Pro it refses the url as invalid WMTS.

Can you somehow find out more about what's going on in both cases? Any logs, error message details. The xcube `WMTSCapabilities.xml` should be valid, e.g. it works fine with OpenLayers.

**Comment by tiagoams** [comment]
Finaly got hold of someone with A ArcGis Pro licence to try this but htere is no error in the logs. As with QGIS, the available variables are shown are shown, but after selecting one, software gets stuck fetching tiles, until timeout.

I understand the explanation, and in the absence of error logs, I don't see the point to keeping this open.

**Comment by forman** [comment]
@tiagoams ok thanks, closing
