### ISSUE TITLE
Flagging differences between xcube and SNAP

### ISSUE THREAD

**Issue by clebreton** [dcs4cop/xcube#479]
There are flagging inconsistencies between SNAP and xcube, with the same valid pixel expression.  I would trust more SNAP in this instance, but of course, SNAP could also be wrong.

example: 03.07.2021 time 09:34 (09:32-09:35 frame) Växjö CyaonAlert Cube. Station Nora Bergundasjön
in the Viewer:

![image](https://user-images.githubusercontent.com/3809213/124432848-5c54be80-dd72-11eb-8ad7-0aea873265a0.png)

in SNAP (cyan pixels are the one valid):
![image](https://user-images.githubusercontent.com/3809213/124432990-8312f500-dd72-11eb-9e1b-8bcdc0139c08.png)

with valid pixel expression applied:
![image](https://user-images.githubusercontent.com/3809213/124434995-d128f800-dd74-11eb-95b2-de58dfb3621d.png)

The config for Växjö is in service-cyanoalert/3_operational/xcube_gen_configs/low_res_configs/water_services/ws-s3-l2-vaxjo-Sweden-v1.yml

The valid expression used in SNAP is:
(not quality_flags.invalid and not pixel_classif_flags.IDEPIX_CLOUD and not pixel_classif_flags.IDEPIX_CLOUD_BUFFER and not pixel_classif_flags.IDEPIX_CLOUD_SHADOW and not pixel_classif_flags.IDEPIX_SNOW_ICE and not (c2rcc_flags.Rtosa_OOS and conc_chl > 1.0) and not c2rcc_flags.Rtosa_OOR and not c2rcc_flags.Rhow_OOR and not (c2rcc_flags.Cloud_risk and immersed_cyanobacteria == 0) and floating_vegetation == 0 and conc_chl > 0.01 and not (floating_cyanobacteria == 1 or chl_pitarch > 500))

File to test  can be found on bcserver13/data/CYANOALERT/olci-l2-nrt/Sweden/2021/07/L2_of_S3A_OL_1_EFR____20210703T093251_20210703T093551_20210703T114806_0179_073_307_1980_MAR_O_NR_002.SEN3.nc
or on feeder: /calvalus/projects/cyanoalert/olci-l2-nrt/Sweden/2021/07/L2_of_S3A_OL_1_EFR____20210703T093251_20210703T093551_20210703T114806_0179_073_307_1980_MAR_O_NR_002.SEN3.nc

Band to test is chl_pci_pitarch

**Comment by forman** [comment]
@clebreton I have problems assiging the images to one another. Do they even have same spatial resolution? 
@AliceBalfanz I removed label "bug" because we haven't found out whether it is one at all and if so, where it originates from, e.g. it could be display problem in xcube-viewer too.  Do we use the same expression for the data cube masking and are the inputs to the masking expression exactly the same?

**Comment by clebreton** [comment]
@forman yes the images have the same resolution. the upper image is from the viewer, the lower two are from the original L2 product opened in SNAP (original resolution of 30mm with geographic lat/lon projection). It is difficult to make a one to one screenshot because then the SNAP screenshot would be all black. That's why I zoomed out a bit in SNAP.
And of course the valid pixel expression is the same for both, this is what I first checked.
I don't see really how this could be a viewer a problem, the viewer cannot invent data that should, per expression when building the cube, not be there.
This is not new, just popped up again because for this particular chlorophyll band I did not generate the pre-flagged band before cube generation.

**Comment by forman** [comment]
> I don't see really how this could be a viewer a problem, the viewer cannot invent data that should, per expression when building the cube, not be there.
Just an example. Could also be a cube generation or xcube server configuration problem. It could also be a problem of data packing which also alters the final data values and hence the masking.

> This is not new, just popped up again because for this particular chlorophyll band I did not generate the pre-flagged band before cube generation.

Since how long? I mean, this is a really severe problem, given it originates from wrong xcube expression evaluation.

**Comment by forman** [comment]
It seems the SNAP you are using is different from what is configured for xcube. The xcube mask is effectively

```
not
(
  (
    pixel_classif_flags.IDEPIX_CLOUD
    or pixel_classif_flags.IDEPIX_CLOUD_BUFFER
    or pixel_classif_flags.IDEPIX_CLOUD_SHADOW
    or pixel_classif_flags.IDEPIX_SNOW_ICE
  )
  or
  (
    quality_flags.invalid
    or quality_flags.land
    and not quality_flags.fresh_inland_water
  )
)
and not
(
  2rcc_flags.Cloud_risk and not immersed_cyanobacteria
  or floating_vegetation
  or floating_cyanobacteria or chl_pitarch > 500
)
and not
(
  c2rcc_flags.Rtosa_OOR
  or c2rcc_flags.Rtosa_OOS and conc_chl < 1.0
  or c2rcc_flags.Rhow_OOR
)
```

Note the `conc_chl < 1.0` which is `conc_chl > 1.0` in the SNAP expression. I guess the xcube exoression is wrong, right?

**Comment by forman** [comment]
xcube also uses `quality_flags.land` and `quality_flags.fresh_inland_water` which are not used in SNAP.

**Comment by clebreton** [comment]
> 
> 
> xcube also uses `quality_flags.land` and `quality_flags.fresh_inland_water` which are not used in SNAP.

We have that more as a security measure, these flags are used during processing already.

**Comment by AliceBalfanz** [comment]
orig pixel expression: 

with adjusted pixel expression

**Comment by forman** [comment]
It was a configuration issue / issue with the data. Closing.
