### ISSUE TITLE
xcube gen2 to produce consolidated datasets

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube#500]
**Is your feature request related to a problem? Please describe.**
Currently cubes, which are generated with `xucbe gen2` do not consolidate the metadata, which means that a lot of request need to be sent to an objectstorage in order to fetch the metadata information.

**Describe the solution you'd like**
I would like `xcube gen2` to produce consolidated datasets including a `.zmetadata` file in the dirs.

**Comment by forman** [comment]
Closed by #502 in xcube 0.9
