### ISSUE TITLE
Improve performance of Time-Series

### ISSUE THREAD

**Issue by TonioF** [dcs4cop/xcube#52]
The performance of the time-series commands is slow, leading to time-outs. This has been observed for all four endpoints.

GET /ts/{dataset}/{variable}/point
POST /ts/{dataset}/{variable}/geometry
POST /ts/{dataset}/{variable}/geometries
POST /ts/{dataset}/{variable}/features

**Comment by forman** [comment]
See also https://github.com/dcs4cop/xcube-viewer/issues/38

**Comment by forman** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Address urgent xcube viewer issues](https://trello.com/c/mKJGImqi/31-address-urgent-xcube-viewer-issues)

**Comment by forman** [comment]
At least the TS extraction using `xcube serve` should benefit from #58

**Comment by forman** [comment]
Closing this. Reopen if performance issue persists.
