### ISSUE TITLE
Support xy_var_names argument in new_grid_mapping_from_dataset

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube#551]
**Is your feature request related to a problem? Please describe.**
Yes, issue is related to a xcube gen2 cube request, which runs into error: 
`raise NotImplementedError('xy_var_names not yet supported')` here: https://github.com/dcs4cop/xcube/blob/c64fa7c3c063b0f6c6ce5f41c042933cf4c0bcbf/xcube/core/gridmapping/dataset.py#L62

related issue see: https://github.com/bcdev/service-eurodatacube/issues/196

Would be great if this is implemented.

**Comment by TonioF** [comment]
Do you want this to be implemented because you need the functionality or because you don't want to run into this error anymore?

**Comment by TonioF** [comment]
Closed by https://github.com/dcs4cop/xcube/commit/2bb056bed0e078083be6a415c4eef631b2885a8f .
