### ISSUE TITLE
Does xcube server for any projected data ?

### ISSUE THREAD

**Issue by ghislainp** [dcs4cop/xcube#567]
**Is your feature request related to a problem? Please describe.**

The documentation indicates that xcube server requires "that have variables that have at least the dimensions and shape (time, lat, lon), in exactly this order;" and that the crs is WGS84.

Does this limitation still apply ?

**Describe the solution you'd like**

Any datacube with (time, y, x) dimension and crs, transform information could be served. This is particularly critical for polar regions.

**Describe alternatives you've considered**

none

**Comment by forman** [comment]
> Does this limitation still apply ?

Sorry, yes it does. But the next version will be able to serve data cubes that use other spatial CRSes like LAEA (EPSG:3035) or UTM. We already have a working and performant prototype.

**Comment by forman** [comment]
@ghislainp we are happy to present [xcube 0.11](https://github.com/dcs4cop/xcube/releases/tag/v0.11.0) that is now capable of serving datasets with any CRS. Well, reasonable CRSes only :)
