### ISSUE TITLE
Allow explicit configuration of datasets served by the S3 store

### ISSUE THREAD

**Issue by pont-us** [dcs4cop/xcube#585]
**Is your feature request related to a problem? Please describe.**

Consider a situation where we want a store to serve data from Zarrs from a very large S3 bucket (millions of files, petabytes of data; e.g. Eodata on Creodias). The usual store creation parameters, `root` and `max_depth`, are insufficient, because:

 - The Zarrs we want to serve are not guaranteed to be grouped under a common prefix
 - A search for Zarrs in a bucket of this size, even starting from the longest common prefix, would take a very long time
 - There may be Zarrs that we wish to exclude from the store, for instance because of known problems with data or compatibility
 - The paths of the Zarrs in the store may have lengthy prefixes and names, and may therefore be inconvenient for users to work with

**Describe the solution you'd like**

I would like to be able to do something like the following:

```python
store = new_data_store('s3', root='some-bucket',
            serve_only={
                'nice-name-1': 'long/messy/path/long-and-messy-name.zarr',
                'nice-name-2': 'some/other/long/path/another-long-name.zarr',
                'nice-name-3': 'i/think/you/get/the-idea.zarr'
            })
```

Supplying the `serve_only` parameter disables automatic data discovery, and serves only the datasets specified in the dictionary values, presenting them to the user under the aliases given by the dictionary keys.

**Describe alternatives you've considered**

 - Creating a separate store for each dataset: inconvenient (especially for large numbers of datasets), doesn't allow aliasing, doesn't allow exclusion of unwanted datasets with the same prefix as wanted datasets
 - Include/exclude list parameters: doesn't allow aliasing; doesn't necessarily disable automatic dataset discovery
 - Implement an external S3 ‘facade’, using the original bucket as a back-end and serving selected Zarrs under selected aliases: more work and more points of failure than implementing the suggested feature directly in xcube.

**Comment by forman** [comment]
> Include/exclude list parameters: doesn't allow aliasing; doesn't necessarily disable automatic dataset discovery

1. The data store abstraction is not intended to _serve_ anything. It is a wrapper for existing services.
2. The limitation applies to file-like stores only. Other data stores don't use file paths at all. In most cases, we don't know the contents of data stores so we cannot create specific aliases.
3. Aliasing is not what is asked for here: we need options to filter datasets. If you need aliasing please create a new feature request.

Therefore I believe lists of `includes` and `excludes` wildcards are the most appropriate and flexible solution here.
