### ISSUE TITLE
DataStore.write_data() to return data opened from written data

### ISSUE THREAD

**Issue by forman** [dcs4cop/xcube#619]
**Is your feature request related to a problem? Please describe.**

As of their docstrings, the `xcube.core.store.DataOpener.write_data()` and `xcube.core.store.DataStore.write_data()` methods return the `data_id` (type `str`) that has been passed as required argument.

1. This is no added value, because `data_id` is a required, positional argument. 
2. Many accessor and store implementations currently return nothing at all (hence `None` is returned)

I'd like to force `write_data()` to return the data retrieved from opening the data that has just been written.
This is especially useful **if data type transformations occur**, for example, an `xr.Dataset` is written using `levels` format, therefore a `MultiLevelDataset` would be returned. This also **helps verifying that the write operation produced a readable result**.
 
**Describe the solution you'd like**

A keyword argument `force_open: bool` (TBD) should be introduced. 

* If `True`, `write_data()` is forced to open (with default open parameters) the written `data` and return the opened data instance.
* If `False`, `write_data()` returns the `data` instance passed in.

This change is not backward compatible. However, xcube does not really use the return value of `write_data()` and as noted above, the return value is not even implemented for some accessors/stores.

**Comment by TonioF** [comment]
1. 'data_id' is not a required argument. If it is not returned, there would be no way of knowing what the data_id would be.
2. Some stores might change/adjust the data_id slightly, e.g., by extending it by an extension.
The changed identifier is to my knowledge at least used by the CCI Toolbox. However, I'd see no problem with returning both, the data and its identifier.
Regarding the force_open-parameter: I'd find it confusing if for 'False' I'd get my input data back. But maybe this is due to the naming which is still set to TBD.

**Comment by forman** [comment]
> Regarding the force_open-parameter: I'd find it confusing if for 'False' I'd get my input data back. But maybe this is due to the naming which is still set to TBD.

In 99% of all cases, you currently get your `data_id` back.

**Comment by TonioF** [comment]
In that case I suggest that we go all the way, make 'data_id' a required parameter and remove any parts from the stores where a data_id is changed.

**Comment by forman** [comment]
Closed by #623.

> In that case I suggest that we go all the way, make 'data_id' a required parameter and remove any parts from the stores where a data_id is changed.

See new #642
