### ISSUE TITLE
DataOpener.write_data() to always return data_id

### ISSUE THREAD

**Issue by forman** [dcs4cop/xcube#623]
**Describe the bug**

Some `DataOpener.write_data()`  implementations (accessors) currently return `None`.  

**To Reproduce**

See impls of 

- `DatasetZarrFsDataAccessor.write_data()`
- `DatasetNetcdfFsDataAccessor.write_data()`
- `MultiLevelDatasetLevelsFsDataAccessor.write_data()`
- `GeoDataFrameFsDataAccessor.write_data()`

**Expected behavior**

Accessors must return `data_id` passed in. 
Let store impl. return return-value from accessors delegates.

**Comment by TonioF** [comment]
Can you please explain shortly how this is helpful in achieving #619?

**Comment by forman** [comment]
> Can you please explain shortly how this is helpful in achieving #619?

I came accross this while solving #619. Edited the PR description so you can accept this without worries.
