### ISSUE TITLE
xarray related projects list

### ISSUE THREAD

**Issue by dcherian** [dcs4cop/xcube#65]
It'd be nice to see xcube on this list of xarray-related projects: https://xarray.pydata.org/en/stable/related-projects.html

Please open a PR if you agree.

**Comment by forman** [comment]
Thanks for the hint! Done: https://github.com/pydata/xarray/compare/stable...forman:patch-1

**Comment by dcherian** [comment]
Thanks! You had to click "create pull request" but I did that :)
