### ISSUE TITLE
WMTSCapabilities - Internal server error (edc-api)

### ISSUE THREAD

**Issue by uwel** [dcs4cop/xcube#673]
**Description:**
WMTSCapabilities request raises internal server error.

**Steps to reproduce the behavior:**
1. Open URL https://edc-api.brockmann-consult.de/api/wmts/1.0.0/WMTSCapabilities.xml in browser.

**Expected behavior:**
XML describing WMTS capabilities.

**Screenshot:**
![grafik](https://user-images.githubusercontent.com/224489/165128077-2c8ecde5-d17e-413e-b252-857add1397bf.png)

**Comment by forman** [comment]
@uwel Thanks for reporting. I'll investigate asap...

**Comment by forman** [comment]
Closed in 0.13.0.dev9
