### ISSUE TITLE
add turbo to supported colormaps

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube#687]
**Is your feature request related to a problem? Please describe.**
Most matplotlib cmaps are supported, but "turbo" is not.

https://github.com/dcs4cop/xcube/blob/master/xcube/util/cmaps.py#L88

Would be great, if we add support for turbo (and maybe other missing ones) as well.

**Comment by pont-us** [comment]
Best of all would be to populate xcube's list directly from the output of `matplotlib.pyplot.colormaps()`, which would ensure that all the current matplotlib colourmaps are supported. Currently matplotlib offers 166 colourmaps, of which xcube only supports 87. Of course this needs integrating with xcube's current division of colourmaps into hand-curated categories -- the simplest approach would be something like

```python
xcube_cmaps = set()
xcube_cmaps.update(*[c[2] for c in _CMAPS])
non_xcube_cmaps = list(set(matplotlib.pyplot.colormaps()) - xcube_cmaps)
_CMAPS = _CMAPS + ("Other colormaps", "colormaps not listed elsewhere", non_xcube_cmaps)
```
