### ISSUE TITLE
Errors when using `xcube serve` with `--show` parameter

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube#750]
**Describe the bug**
When following the description (https://xcube.readthedocs.io/en/latest/examples/xcube_serve.html#id1) how to use xcube-viewer together with `xcube serve` and `--show` parameter, the dataset is not shown, but an error message appears in the browser window: 
`The connection was reset`
![image](https://user-images.githubusercontent.com/23457217/195843866-ab2e916c-0e67-4102-ac07-299f65c14285.png)

xcube serve shows nothing in the logs after starting the server: 
![image](https://user-images.githubusercontent.com/23457217/195844206-b5483e8c-cd92-493d-83fa-76648974f95a.png)

**To Reproduce**
Follow documentation: https://xcube.readthedocs.io/en/latest/examples/xcube_serve.html#id1

**Comment by forman** [comment]
Latest versions of `xcube serve` (aka xcube Server NG) no longer support the `--show` option. We may reintroduce it, but then with a packaged viewer build. Closing this issue.

**Comment by forman** [comment]
Will mention that in changelog.
