### ISSUE TITLE
Reading '.levels' files from Azure blob storage

### ISSUE THREAD

**Issue by edd3x** [dcs4cop/xcube#752]
I have xcube server running via a web-app container on MS Azure, and my datasets are saved as '.levels' files and linked to their corresponding 'zarr' files in Azure blob storage. The server loads and displays the '.zarr' files with no issues, but I always get "_The specified resource does not exis_t" error when I set config path files to read level files. I thought the issue was with the "0.link" file so I set the link path to the full URL to the zarrs on the blob storage, but I still get the errors. What can I do to fix this? 

Thanks

Edward

**Comment by forman** [comment]
Hi Edward, can you please share the relevant parts of your server configuration?

**Comment by edd3x** [comment]
Hi Forman, 
Thanks, I solved the earlier issue by listing both .zarr and .levels in the server config and then setting the .zarr file to hidden, 
Like this:
Datasets:
  - Identifier:  S2_T30VVJ
    Title: "S2 NDVI Cairngorms All Vars"
    FileSystem: s3
    Endpoint: "https:/blob.core.windows.net"
    Path: "/zarr-levels/Cairngorms_T30VVJ_all_stack.zarr"
    Anonymous: true
    Hidden: true
    TimeSeriesDataset: S2_T30VVJ_Timeseries
    Style: default

  - Identifier:  S2_T30VVJ
    Title: "S2 NDVI Cairngorms All Vars Level"
    FileSystem: s3
    Endpoint: "https://blob.core.windows.net"
    Path: "/zarr-levels/Cairngorms_T30VVJ_all_stack.levels"
    Anonymous: true
    TimeSeriesDataset: S2_T30VVJ_Timeseries
    Style: default

**Comment by edd3x** [comment]
Hi Alice, 
No it's not local, I am listing reading directly from the Azure blob storage. Sorry the endpoint URI is not correct it has an error this is the correct one, https://stuos4epdata01.blob.core.windows.net. 

I understand that the xcube was built for AWS but is it possible to add a function to list azure blob files for xcube to read via the datastore approach?

**Comment by forman** [comment]
It seems we just need to add a new filesystem-based data store, `adlfs`, should be straight forward, see https://github.com/fsspec/adlfs.

@edd3x would you volunteer for testing?

**Comment by edd3x** [comment]
@forman Yes, I would like to volunteer to test. Thanks

**Comment by edd3x** [comment]
@forman, I if the feature has been added and when I can start testing it, 
Thanks

**Comment by forman** [comment]
Closed in 1.0.0.dev3
