### ISSUE TITLE
Use micromamba for CI builds, rather than miniconda + mamba

### ISSUE THREAD

**Issue by pont-us** [dcs4cop/xcube#785]
At present, AppVeyor and GitHub workflow builds use mamba installed via miniconda. This requires about three minutes of installation time, which could be saved by using the self-contained alternative [micromamba](https://mamba.readthedocs.io/en/latest/user_guide/micromamba.html). Micromamba has been in use for the xcube-cds and nc2zarr AppVeyor builds for over a year without any problems, so it seems fairly solid despite being officially "experimental".

Note also that [the current mamba documentation](https://mamba.readthedocs.io/en/latest/installation.html) strongly recommends against installing mamba via conda-forge. (The recommended method these days for those who don't want to use micromamba is with [mambaforge](https://github.com/conda-forge/miniforge#mambaforge).)

**Comment by forman** [comment]
See also: https://github.com/dcs4cop/xcube/pull/820
