### ISSUE TITLE
xcube server endpoints documentation via openapi.html

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube#793]
**Is your feature request related to a problem? Please describe.**
I would love a more detailed description of the xcube server endpoints :)

**Describe the solution you'd like**
A summary for 

- [x] /places

provide mandatory query parameters for 

- [x]  /places/{placeGroupId}
- [x] /places/{placeGroupId}/{datasetId}
- [x] /datasets/{datasetId}
- [x] /datasets/{datasetId}/coords/{dimName}
- [x] /datasets/{datasetId}/places/{placeGroupId}
- [x] /tiles/{datasetId}/{varName}/legend
- [x] /tiles/{datasetId}/{varName}/{z}/{y}/{x}
- [x] /timeseries/{datasetId}/{varName}
- [x] /wmts/1.0.0/{tmsId}/WMTSCapabilities.xml
- [x] /wmts/1.0.0/tile/{datasetId}/{varName}/{z}/{y}/{x}.png
- [x] /wmts/1.0.0/tile/{datasetId}/{varName}/{tmsId}/{z}/{y}/{x}.png

**Comment by forman** [comment]
> provide mandatory query parameters for

Mostly _path_ parameters are missing, not _query_.
