### ISSUE TITLE
`xcube server`: specify variable to be displayed by default in xcube viewer

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube#835]
**Is your feature request related to a problem? Please describe.**
When I publish a dataset via xcube server which is then visualised by xcube viewer, the variables are variables in the drop down menu are sorted alphabetically. And per default the first variable in the list is visualised. However, this is not always an variable of interest for the user of xcube viewer. 

**Describe the solution you'd like**
I would like to be able to specify a variable which should be used per default in xcube viewer. To achieve this, I would like to be able to specify it in the xcube server configuration yaml file or also be able to indicate the default variable already in the datasets metadata. 

**Describe alternatives you've considered**
Currently there is no alternative to this. 

**Additional context**

**Comment by forman** [comment]
I agree. We have a same requirement for the STAC catalog where we would need to define the variable that provides a representative quicklook image for the dataset.
