### ISSUE TITLE
`xcube serve` specify initial bounding box displayed in xcube viewer 

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube#845]
**Is your feature request related to a problem? Please describe.**
For some datasets the initially shown fragment in xcube viewer is not appropriate.

For example SMOS data is saved in a polar CRS, which the viewer can deal with, however it displays Antarctica initially, although there is no data there: 
![image](https://user-images.githubusercontent.com/23457217/229529618-75a1534d-f9b5-4d93-b7a6-0bfc802dca49.png)

One has to manually change the view every time. 

**Describe the solution you'd like**
 I would like to specify in the server configuration a bounding box, which is used for the initial display of a dataset in the xcube viewer 
![image](https://user-images.githubusercontent.com/23457217/229530313-caad107d-51cd-4b03-8c8d-b08782cda82f.png)

**Describe alternatives you've considered**
There is no alternative. 

**Additional context**

**Comment by forman** [comment]
Hey @AliceBalfanz, we can already specify the geographic bounding box in the server configuration. However, I just realized that it is recognised only when dataset lists are requested but it is ignored, when requesting the details of a specific dataset. Easily fixed...
