### ISSUE TITLE
Allow filtering by assigning a variable related to a polygon

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube#85]
**Is your feature request related to a problem? Please describe.**
Assign to a given polygon a dedicated list of variables (to be displayed on the viewer) from the available variables in the generated cube.

***A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]***
the idea is that we do not show at all places all the available layers for the same variable like we do now in the viewer.

**Comment by AliceBalfanz** [comment]
write petra

**Comment by forman** [comment]
Closed in favor of https://github.com/dcs4cop/xcube-viewer/issues/69
