### ISSUE TITLE
conda install not working

### ISSUE THREAD

**Issue by gdkrmr** [dcs4cop/xcube#856]
```
[gkraemer@orange py]$ conda create -c conda-forge -n xcube xcube
Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: / 
```
just keeps on solving forever.

**Comment by janneskruse** [comment]
Having the same issue. This happens is for any version returned via conda search -c conda-forge xcube. Also maybe interesting: On pip there is a package named [xcube 0.0.1](https://pypi.org/project/xcube/) with a different purpose, which can be confusing.

**Comment by AliceBalfanz** [comment]
@gdkrmr and @janneskruse thanks for reporting, please consider using mamba instead of conda:
https://xcube.readthedocs.io/en/latest/installation.html#installation-using-mamba

we experience way faster installation with mamba :)

**Comment by janneskruse** [comment]
> @gdkrmr and @janneskruse thanks for reporting, please consider using mamba instead of conda: https://xcube.readthedocs.io/en/latest/installation.html#installation-using-mamba
> 
> we experience way faster installation with mamba :)

Thank you @AliceBalfanz !
Mamba solved the xcube installation problem but now I am having some issues with _aiohttp_ throwing _AttributeError: module 'aiohttp' has no attribute 'http_exceptions'_

I am trying to open this cube:

```
from xcube.core.store import new_data_store
store = new_data_store("s3", root="deep-esdl-public", storage_options=dict(anon=True))
ds = store.open_data('ocean-1M-9km-1x1080x1080-1.4.0.zarr')

```

Do you know if I need a specific version of aiohttp?

**Comment by AliceBalfanz** [comment]
@janneskruse with `aiohttp 3.8.4` there are no issues, which version do you use? 
By the way, I see you are using the deep-esdl cube, but you are not one of our deepesdl jupyterlab users yet - there you would have functioning python environments preconfigured already  :) Let us know, in case you are interested in being onboarded!
