### ISSUE TITLE
xcube cannot access geotiff datasets from public buckets

### ISSUE THREAD

**Issue by TonioF** [dcs4cop/xcube#893]
**To Reproduce**
1. Create an xcube store to geotiff datasets stored in a public s3 bucket (e.g., from here: https://registry.opendata.aws/copernicus-dem/ )
3. Open one of the datasets (ds = store.open_data(...) )
4. Try to open the base_dataset: ds.base_dataset
5. You'll receive this error: AttributeError: 'NoneType' object has no attribute 'Session'

It seems this error only occurs when boto3 is not installed. Also, it started appearing with xcube 1.1.2.

**Comment by pont-us** [comment]
Confirmed with a fresh xcube 1.2.0 insetall from conda-forge and the following code.

```python
import xcube.core.store

datastore = xcube.core.store.new_data_store(
    's3',
    root='copernicus-dem-30m'
)

dataset = datastore.open_data(
    'Copernicus_DSM_COG_10_S15_00_E143_00_DEM/'
    'Copernicus_DSM_COG_10_S15_00_E143_00_DEM.tif'
)

print(dataset.base_dataset)
```
